### ISSUE TITLE
Installation Problem / Error: Failed loading extension "featherlight"

### ISSUE THREAD

**Issue by tmeuze** [it-novum/mkdocs-featherlight#3]
Hello, 

I had issues installing mkdocs-featherlight on both Ubuntu (GitHub Actions) and macOS, using the instructions:
`pip3 install -e git+https://github.com/it-novum/mkdocs-featherlight.git`

Resulting in:
```
ERROR: Could not detect requirement name for 'git+https://github.com/it-novum/mkdocs-featherlight.git', please specify one with #egg=your_package_name
```

I was able to install without error by appending `#egg=featherlight`

However, mkdocs refuses to serve, with a vague error (even in verbose mode):
```
ERROR - Config value: 'markdown_extensions'. Error: Failed loading extension "featherlight"
```

This also happens when I use the alternative (manual) installation method. 

I'd greatly appreciate any insight into this, or if you know of any way to further debug this.

**Comment by nook24** [comment]
It is wokring for me using `Python 3.9.7` and `pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)`

Our documentation is installing it the same way:
https://github.com/it-novum/openITCOCKPIT-documentation/blob/dcdac1d64049a9adeb127ea55fe0d0c9d895e047/Dockerfile#L4-L7

What python version do you use?
You could try this:
```
pip3 install -e git+https://github.com/it-novum/mkdocs-featherlight.git#egg=featherlight
```

**Comment by tmeuze** [comment]
Thank you for your response! Unfortunately, the same error persists after trying that. It installs, but `mkdocs serve|build` errors out.  

I am on `Python 3.9.9`, `Pip 22.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)`. Do you suppose the version is the issue?

![CleanShot 2022-05-18 at 15 44 21](https://user-images.githubusercontent.com/9298659/169144023-f6ab2303-3de7-4a28-b1d4-9ab3f44baf30.png)

I don't know much at all about Python, but I tried a `--user` install as well (why not).

**Comment by nook24** [comment]
To be honest, i don't' know. I have never tested this on macOS or with an homebrew installation of python.

**Comment by tmeuze** [comment]
Turns out, it was a PATH issue, along with appending the `#egg=featherlight`. Thanks so much for your help!

**Comment by tmeuze** [comment]
Also, thanks for making this plugin!

**Comment by nook24** [comment]
You are welcome
